import { apiRequest } from "@/lib/api";
import type { 
  Subscription, 
  CreateSubscriptionInput, 
  SubscriptionOrder, 
  SubscriptionPayment 
} from "@/types/subscription";

/** List all subscriptions for current user */
export async function getSubscriptions(): Promise<Subscription[]> {
  return apiRequest<Subscription[]>("/api/subscriptions/");
}

/** Create a new recurring subscription */
export async function createSubscription(data: CreateSubscriptionInput): Promise<Subscription> {
  return apiRequest<Subscription>("/api/subscriptions/", {
    method: "POST",
    body: JSON.stringify(data),
  });
}

/** Retrieve detail for a specific subscription */
export async function getSubscription(id: string): Promise<Subscription> {
  return apiRequest<Subscription>(`/api/subscriptions/${id}/`);
}

/** Pause an active subscription */
export async function pauseSubscription(id: string): Promise<Subscription> {
  return apiRequest<Subscription>(`/api/subscriptions/${id}/pause/`, { method: "POST" });
}

/** Resume a paused subscription */
export async function resumeSubscription(id: string): Promise<Subscription> {
  return apiRequest<Subscription>(`/api/subscriptions/${id}/resume/`, { method: "POST" });
}

/** Permanently cancel a subscription */
export async function cancelSubscription(id: string): Promise<Subscription> {
  return apiRequest<Subscription>(`/api/subscriptions/${id}/cancel/`, { method: "POST" });
}

/** Get my subscriptions (Buyer specific) */
export async function getMySubscriptions(): Promise<Subscription[]> {
  return apiRequest<Subscription[]>("/api/subscriptions/my_subscriptions/");
}

/** List orders generated by subscriptions */
export async function getSubscriptionOrders(): Promise<SubscriptionOrder[]> {
  return apiRequest<SubscriptionOrder[]>("/api/subscription-orders/");
}

/** List payments associated with subscription orders */
export async function getSubscriptionPayments(): Promise<SubscriptionPayment[]> {
  return apiRequest<SubscriptionPayment[]>("/api/subscription-payments/");
}
