import { create } from 'zustand';
import type { Product } from '../../types/marketplace';

interface ProductState {
  products: Product[];
  setProducts: (products: Product[]) => void;
  // We can add filtering/sorting states here later
}

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 1,
    name: "Heritage Roma Tomatoes",
    farm: "Green Valley Farms, CA (17 mi)",
    location: "Green Valley, CA",
    price: "$3.50",
    unit: "kg",
    badge: "AI ↑ 5%",
    badgeColor: "gold",
    harvestDate: "Dec 08, 2025",
    available: "In stock",
    image: "https://images.unsplash.com/photo-1546094096-0df4bcaaa337?w=400&q=70",
    organic: true,
  },
  {
    id: 2,
    name: "Organic Carrots",
    farm: "Sunpower Organics",
    location: "Fresno, CA",
    price: "$1.30",
    unit: "kg",
    badge: "Organic",
    badgeColor: "green",
    harvestDate: "Dec 10, 2025",
    available: "In stock",
    image: "https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=400&q=70",
    aiTag: "High demand predicted",
  },
  {
    id: 3,
    name: "Bell Pepper Mix",
    farm: "Riverside Cooperative",
    location: "Riverside, CA",
    price: "$4.80",
    unit: "kg",
    badge: "RESTOCKED",
    badgeColor: "blue",
    harvestDate: "Dec 12, 2025",
    available: "Limited",
    image: "https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?w=400&q=70",
  },
  {
    id: 4,
    name: "Leafy Kale Bunch",
    farm: "River Heart Harvest",
    location: "Salinas, CA",
    price: "$2.35",
    unit: "ea",
    harvestDate: "Dec 14, 2025",
    available: "Bundles: 250g per bunch",
    image: "https://images.unsplash.com/photo-1524179091875-bf99a9a6af57?w=400&q=70",
    organic: true,
  },
  {
    id: 5,
    name: "Sweet Corn",
    farm: "Prairie Gold Farms",
    location: "Stockton, CA",
    price: "$0.80",
    unit: "ea",
    badge: "Seasonal",
    badgeColor: "gold",
    harvestDate: "Dec 09, 2025",
    available: "In stock",
    image: "https://images.unsplash.com/photo-1551754655-cd27e38d2076?w=400&q=70",
  },
  {
    id: 6,
    name: "Zucchini",
    farm: "Hillside Gardens",
    location: "Modesto, CA",
    price: "$2.10",
    unit: "kg",
    harvestDate: "Dec 11, 2025",
    available: "In stock",
    image: "https://images.unsplash.com/photo-1596097635121-14b63b7a0c19?w=400&q=70",
    outOfStock: false,
  },
  {
    id: 7,
    name: "Organic Russet Potatoes",
    farm: "Green Acres Farm • Grade A",
    location: "Idaho Falls, ID",
    price: "$0.45",
    unit: "kg",
    harvestDate: "Dec 05, 2025",
    available: "In stock",
    image: "https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=400&q=70",
    organic: true,
  },
  {
    id: 8,
    name: "Red Bulb Onions",
    farm: "Valley Harvest Co-op",
    location: "Walla Walla, WA",
    price: "$1.20",
    unit: "kg",
    harvestDate: "Dec 01, 2025",
    available: "In stock",
    image: "https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?w=400&q=70",
  },
  {
    id: 9,
    name: "Fine Green Beans",
    farm: "Sunrise Orchards",
    location: "Portland, OR",
    price: "$2.10",
    unit: "kg",
    harvestDate: "Dec 12, 2025",
    available: "In stock",
    image: "https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?w=400&q=70",
  },
];

export const useProductStore = create<ProductState>((set) => ({
  products: INITIAL_PRODUCTS,
  setProducts: (products) => set({ products }),
}));
